//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace logviewer.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("logviewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drag chart axis column here ähnelt.
        /// </summary>
        public static string ChartEditor_AxisDragTarget {
            get {
                return ResourceManager.GetString("ChartEditor_AxisDragTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drag series columns here ähnelt.
        /// </summary>
        public static string ChartEditor_SeriesDragTarget {
            get {
                return ResourceManager.GetString("ChartEditor_SeriesDragTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application ähnelt.
        /// </summary>
        public static string Dialogs_Application {
            get {
                return ResourceManager.GetString("Dialogs_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bookmark will be removed ähnelt.
        /// </summary>
        public static string Dialogs_BookmarkWillBeRemoved {
            get {
                return ResourceManager.GetString("Dialogs_BookmarkWillBeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CANCEL ähnelt.
        /// </summary>
        public static string Dialogs_CancelButton {
            get {
                return ResourceManager.GetString("Dialogs_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CLOSE ähnelt.
        /// </summary>
        public static string Dialogs_CloseButton {
            get {
                return ResourceManager.GetString("Dialogs_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy from file to application ähnelt.
        /// </summary>
        public static string Dialogs_CopyFromFile {
            get {
                return ResourceManager.GetString("Dialogs_CopyFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy from application to file ähnelt.
        /// </summary>
        public static string Dialogs_CopyToFile {
            get {
                return ResourceManager.GetString("Dialogs_CopyToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DELETE ähnelt.
        /// </summary>
        public static string Dialogs_DeleteButton {
            get {
                return ResourceManager.GetString("Dialogs_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This action cannot be undone! ähnelt.
        /// </summary>
        public static string Dialogs_DeleteMessage {
            get {
                return ResourceManager.GetString("Dialogs_DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to delete the item? ähnelt.
        /// </summary>
        public static string Dialogs_DeleteView {
            get {
                return ResourceManager.GetString("Dialogs_DeleteView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Documentation ähnelt.
        /// </summary>
        public static string Dialogs_Documentation {
            get {
                return ResourceManager.GetString("Dialogs_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit query... ähnelt.
        /// </summary>
        public static string Dialogs_EditPanel {
            get {
                return ResourceManager.GetString("Dialogs_EditPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        public static string Dialogs_File {
            get {
                return ResourceManager.GetString("Dialogs_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help &amp; About ähnelt.
        /// </summary>
        public static string Dialogs_Help {
            get {
                return ResourceManager.GetString("Dialogs_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Licensing ähnelt.
        /// </summary>
        public static string Dialogs_Licensing {
            get {
                return ResourceManager.GetString("Dialogs_Licensing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage Bookmarks ähnelt.
        /// </summary>
        public static string Dialogs_ManageBookmarks {
            get {
                return ResourceManager.GetString("Dialogs_ManageBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OPEN ähnelt.
        /// </summary>
        public static string Dialogs_OpenButton {
            get {
                return ResourceManager.GetString("Dialogs_OpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A query with the given name is already existing and will be overwritten ähnelt.
        /// </summary>
        public static string Dialogs_OverwriteMessage {
            get {
                return ResourceManager.GetString("Dialogs_OverwriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove from file ähnelt.
        /// </summary>
        public static string Dialogs_RemoveFromFile {
            get {
                return ResourceManager.GetString("Dialogs_RemoveFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove from local storage ähnelt.
        /// </summary>
        public static string Dialogs_RemoveFromLocalStorage {
            get {
                return ResourceManager.GetString("Dialogs_RemoveFromLocalStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SAVE ähnelt.
        /// </summary>
        public static string Dialogs_SaveButton {
            get {
                return ResourceManager.GetString("Dialogs_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ALL ähnelt.
        /// </summary>
        public static string Dialogs_SelectAllButton {
            get {
                return ResourceManager.GetString("Dialogs_SelectAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title ähnelt.
        /// </summary>
        public static string Dialogs_Title {
            get {
                return ResourceManager.GetString("Dialogs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add bookmark ähnelt.
        /// </summary>
        public static string Menu_AddBookmark {
            get {
                return ResourceManager.GetString("Menu_AddBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bookmark repository ähnelt.
        /// </summary>
        public static string Menu_BookmarkRepository {
            get {
                return ResourceManager.GetString("Menu_BookmarkRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bookmarks ähnelt.
        /// </summary>
        public static string Menu_Bookmarks {
            get {
                return ResourceManager.GetString("Menu_Bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear selection ähnelt.
        /// </summary>
        public static string Menu_ClearBookmarkRepositoryFile {
            get {
                return ResourceManager.GetString("Menu_ClearBookmarkRepositoryFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close tab ähnelt.
        /// </summary>
        public static string Menu_CloseTab {
            get {
                return ResourceManager.GetString("Menu_CloseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open new tab ähnelt.
        /// </summary>
        public static string Menu_CreateTab {
            get {
                return ResourceManager.GetString("Menu_CreateTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Duplicate tab ähnelt.
        /// </summary>
        public static string Menu_DuplicateTab {
            get {
                return ResourceManager.GetString("Menu_DuplicateTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Find bookmark... ähnelt.
        /// </summary>
        public static string Menu_FindBookmark {
            get {
                return ResourceManager.GetString("Menu_FindBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help &amp; About ähnelt.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage bookmarks ähnelt.
        /// </summary>
        public static string Menu_ManageBookmarks {
            get {
                return ResourceManager.GetString("Menu_ManageBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open bookmarks in new tab ähnelt.
        /// </summary>
        public static string Menu_OpenInNewTab {
            get {
                return ResourceManager.GetString("Menu_OpenInNewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open log files ähnelt.
        /// </summary>
        public static string Menu_OpenLogFiles {
            get {
                return ResourceManager.GetString("Menu_OpenLogFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        public static string Menu_Search {
            get {
                return ResourceManager.GetString("Menu_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select file ähnelt.
        /// </summary>
        public static string Menu_SelectBookmarkRepositoryFile {
            get {
                return ResourceManager.GetString("Menu_SelectBookmarkRepositoryFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use dark color scheme ähnelt.
        /// </summary>
        public static string Menu_UseDarkColorScheme {
            get {
                return ResourceManager.GetString("Menu_UseDarkColorScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy line ähnelt.
        /// </summary>
        public static string Search_Copy {
            get {
                return ResourceManager.GetString("Search_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter a query... ähnelt.
        /// </summary>
        public static string Search_Prompt {
            get {
                return ResourceManager.GetString("Search_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset zoom &amp; pan ähnelt.
        /// </summary>
        public static string Search_ResetZoomAndPan {
            get {
                return ResourceManager.GetString("Search_ResetZoomAndPan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run query ähnelt.
        /// </summary>
        public static string Search_RunQuery {
            get {
                return ResourceManager.GetString("Search_RunQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save query to file ähnelt.
        /// </summary>
        public static string Search_SaveQuery {
            get {
                return ResourceManager.GetString("Search_SaveQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save data to file ähnelt.
        /// </summary>
        public static string Search_SaveToFile {
            get {
                return ResourceManager.GetString("Search_SaveToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show details ähnelt.
        /// </summary>
        public static string Search_ShowDetails {
            get {
                return ResourceManager.GetString("Search_ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show tail of results ähnelt.
        /// </summary>
        public static string Search_TailResults {
            get {
                return ResourceManager.GetString("Search_TailResults", resourceCulture);
            }
        }
    }
}
